<?php
$lang = array(


        'title' => array(
                'create_account' => 'Register',
                'customer_login' => 'Log in',
                'customer_register_login' => 'Log in',
                'edit_account' => 'Personal data edit',
                'change_password' => 'Change password',
                'your_account' => 'Your account',
                'delete_password' => 'Delete account',
                'recover_password' => 'Recover password',
                'favourite' => 'Ulubione',
                'customer_login' => 'Log in',
                'orders_history' => 'Transactions history',
				'your_subscriptions' => 'Your subscriptions',
        ),

        'description' => array(
                'create_account' => 'Register',
                'customer_register_login' => 'Log in',
                'edit_account' => 'Personal data edit',
                'change_password' => 'Change password',
                'delete_password' => 'UDelete account',
                'recover_password' => 'Recover password',
                'favourite' => 'Ulubione',
                'customer_login' => 'Log in',
                'orders_history' => 'Transactions history',
				'your_subscriptions' => 'Your subscriptions',
        ),

        'keywords' => array(
                 'create_account' => 'Register',
                'customer_register_login' => 'Log in',
                'edit_account' => 'Personal data edit',
                'change_password' => 'Change password',
                'delete_password' => 'UDelete account',
                'recover_password' => 'Recover password',
                'favourite' => 'Ulubione',
                'customer_login' => 'Log in',
                'orders_history' => 'Transactions history',
				'your_subscriptions' => 'Your subscriptions',
        ),



        'titles' => array(
                'customers_index' => 'Lista klientów - 4dminix CMS by Olicom',
                'edit_customer' => 'Edycja klienta - 4dminix CMS by Olicom',
        ),

        'logout' => 'Log out',
        'delete' => 'Delete',
        'selected' => 'Chcecked',
        'last_name' => 'Last name',
        'first_name' => 'First name',
        'email' => 'E-mail',
        'actions' => 'Options',
        'back' => 'Back',
        'save_changes' => 'Save',
        'client_data' => 'Personal data',
        'registration' => 'Registration',
        'register' => 'Register',
        'login' => 'Log in >>',
        'login_title' => 'Log in',
        'password_recover_title' => 'Password reset',
        'your_data' => 'Your personal data',
        'orders_history' => 'Orders history',
        'order_details' => 'Order details',
        'order_number' => 'Order nr - ',
		'your_subscriptions' => 'Your subscriptions',
		'reg_accept' => 'I accept ',
		'regulamin' => 'regulations',
		'and' => ' and ',
		'policy' => 'privacy Policy',
		'reg_accept2' => 'I hereby agree to the processing of my personal data included in this form to conduct business online in accordance with the Act from 29.08.1997 on the Protection of Personal Data (Journal of Laws of 2002 No.101, item 926, as amended). You have the right to access, change or delete your data.',
		'accept3'=>'I agree to receive commercial information and newsletters',
		'req_fields' =>'Required fields',
		'reg_accept2_nologgin' => 'I hereby agree to the processing of my personal data included in this form to conduct business online in accordance with the Act from 29.08.1997 on the Protection of Personal Data (Journal of Laws of 2002 No.101, item 926, as amended) . Providing this information is optional. You have the right to access, change or delete your data.',

        'gender' => 'Gender',
        'male' => 'Male',
        'female' => 'Female',
        'company_name' => 'Company name',
        'nip' => 'NIP',
        'city' => 'City',
		'adres' => 'Adress',
		'postcode' => 'Postcode',
        'zip' => 'Zip',
		'adres_dost' => 'Delivery address',
		'adres_inny' => 'check if delivery address is different',
        'address' => 'Address',
        'state' => 'State',
        'www' => 'WWW',
		'phone' => 'Phone',
        'phone_no' => 'Phone',
        'fax_no' => 'Fax',
        'mobile_no' => 'Mobile',
        'delivery_address' => 'Delivery address',
        'invoice_address' => 'Invoice address',
        'country' => 'Country',
        'rebate' => 'Rebate',
        'change_password' => 'Change password',


        'account_title' => 'Yout account',

        'email_repeat' => 'Email repeat',
        'password' => 'Password',
        'password_repeat' => 'Password repeat',
        'password_recover' => 'Password recover',

        'edit_customer' => 'Edit customer',

        'no_customers' => 'No customers',

        'change_customer_details' => 'Change customer details',
        'change_details' => 'Change details',
        'watch' => 'Watch',
        'favourite' => 'Favourite',
        'no_favs' => 'No products.',
        'basket' => 'Cart',
        'delete_account' => 'Delete account',

        'delete_account_title' => 'Delete account',

        'account_delete_info' => 'Enter password to delete account.',

        'forgot_password' => 'Forgot your password?',
        'please_register' => 'please register',
        'login_info' => 'Jeśli jeszcze nie posiadasz konta, a chcesz mieć ułatwienia w wypełnianiu formularzy',

        'change_password_title' => 'Change password',
        'old_password' => 'Old password',
        'new_password' => 'New password',
        'new_password_repeat' => 'Repeat new password',

        'delete_success' => 'Delete success.',
        'delete_error' => 'Wystąpił błąd podczas usuwania klienta.',
        'update_producer_success' => 'Customer data updated.',
        'update_producer_error' => 'An error occurred while deleting a customer.',
        'insert_customer_success' => 'Registration was successful. On the specified email a registration confirm message has been sent. Please login to continue purchases.',
        'insert_customer_error' => 'An error occurred while registering.',

        'client_delivery_data' => 'Dane do wysyłki',
        'client_invoice_data' => 'Dane do faktury',

        'validation' => array(
                'following_errors' => 'The following errors occurred',
                'error_customer_email_empty' => 'Field <strong>E-mail</strong> cannot be empty.',
                'error_customer_email_repeat_empty' => 'Field <strong>Powtórz e-mail</strong> cannot be empty.',
                'error_customer_password_empty' => 'Field <strong>Password</strong> cannot be empty.',
                'error_customer_password_repeat_empty' => 'Field <strong>Password repeat</strong> cannot be empty.',
                'error_customer_password_too_short' => 'Password must be at least 6 characters.',
                'error_customer_password_repeat_too_short' => 'Repeated password must be at least of 6 characters.',
                'error_customer_email_format' => 'Incorrect <strong>E-mail</strong> format.',
                'error_customer_email_repeat_format' => 'Nieprawidłowy format adresu w polu <strong>Powtórz e-mail</strong>.',
                'error_wrong_customer_email_repeat' => 'E-mail addresses must be the same.',
                'error_wrong_customer_password_repeat' => 'Passwords must be identical.',
                'customer_exists' => 'The customer with the specified e-mail already exists.',
                'customer_not_exists' => 'The customer with the specified e-mail does not exist.',
                'error_customer_exists' => 'An error occurred while checking if the customer already exists.',

                'wrong_email_or_password' => 'Incorrect e-mail or password.',
                'success_login' => 'You were correctly logged in.',

                'error_logout' => 'An error occurred while logging out.',
                'success_logout' => 'You were correctly logged.',

                'customer_email_not_exist' => 'The specified e-mail address does not exist in the database.',
                'success_recover_password' => 'The new password has been sent.',
                'error_recover_password' => 'An error occurred while generating a new password.',


                'error_old_password_empty' => 'Field <strong>Old password</strong> cannot be empty.',
                'error_new_password_empty' => 'Field <strong>New password</strong> cannot be empty.',
                'error_new_password_repeat_empty' => 'Field <strong>repeat new password</strong> cannot be empty.',
                'error_customer_old_password_too_short' => 'Old password must be at least 6 characters.',
                'error_customer_new_password_too_short' => 'New password must be at least 6 characters.',
                'error_customer_new_password_repeat_too_short' => 'Repeated password must be at least 6 characters.',
                'error_wrong_password' => 'Password incorrect.',
                'error_wrong_new_password_repeat' => 'Repeated password and the new password must be the same.',
                'error_reg_not_confirmed' => 'You must accept <strong>regulations and privacy policy</strong>',
				'error_reg_not_confirmed2' => 'You must accept <strong> terms</strong>!',

                'delete_from_fav_success' => 'Usunięto z ulubionych.',
                'delete_from_fav_error' => 'Wystąpił błąd podczas usuwania z ulubionych.',

                'delete_account_success' => 'Your account has been deleted.',
                'delete_account_error' => 'An error occurred while deleting an account.',

                'please_login_to_add_to_fav' => 'Musisz się zalogować żeby dodać produkt do ulubionych.',

        ),
        'different_delivery_address' => 'Different delivery address',
        'different_invoice_address' => 'Different invoice address',
        'invoice' => 'Faktura VAT',
        'customer_email' => 'Email',
        'customer_city' => 'Miasto',
        'customer_zip' => 'Kod pocztowy',
        'customer_address' => 'Adres',
        'customer_state' => 'Województwo',
        'customer_phoneno' => 'Numer telefonu',
        'order_notes' => 'Order notes',
        'delivery_first_name' => 'Imię',
        'delivery_last_name' => 'Nazwisko',
        'delivery_email' => 'Email',
        'delivery_company_name' => 'Nazwa firmy',
        'delivery_nip' => 'NIP',
        'delivery_city' => 'Miasto',
        'delivery_zip' => 'Kod pocztowy',
        'delivery_state' => 'Województwo',
        'delivery_country' => 'Państwo',
        'delivery_phoneno' => 'Numer telefonu',
        'delivery_faxno' => 'Numer faksu',
        'delivery_mobileno' => 'Numer telefonu komórkowego',
        'invoice_first_name' => 'Imię do faktury',
        'invoice_last_name' => 'Nazwisko do faktury',
        'invoice_email' => 'Email do faktury',
        'invoice_company_name' => 'Nazwa firmy do faktury',
        'invoice_nip' => 'NIP do faktury',
        'invoice_city' => 'Miasto do faktury',
        'invoice_zip' => 'Kod pocztowy do faktury',
        'invoice_state' => 'Województwo do faktury',
        'invoice_country' => 'Państwo do faktury',
        'invoice_phoneno' => 'Numer telefonu do faktury',
        'invoice_faxno' => 'Numer faksu',
        'invoice_mobileno' => 'Numer telefonu komórkowego',
    
    'field_required' => 'Fields required',
    'password_recovery' => 'If you forget the password or want to change it enter the below e-mail address.',
    
    'user_registered' => array(
            'mail_title' => 'Welcome to our shop.',
            'customer_details' => 'During registration you provided the following data:',
            'login' => 'Login:',
            'password' => 'Password:',
            'safe_details' => 'Please keep this data in a safe place.',
            'confirm_click' => 'To confirm your registration, and activate your account, click on the link below or paste it into your web browser:',
            'update_details' => 'In order to improve the use of the site in the future, please complete data within your account. You can do this after logging in your account panel.',
        ),
    
    'account_confirmed' => 'Your account has been activated',    
    'confirm_error' => 'Invalid verification string or an account has already been activated.',
);