<?php
$lang = array(


        'title' => array(
                'create_account' => 'Rejestracja',
                'customer_login' => 'Logowanie',
                'customer_register_login' => 'Logowanie',
                'edit_account' => 'Edycja danych',
                'change_password' => 'Zmień hasło',
                'your_account' => 'Twoje konto',
                'delete_password' => 'Usuwanie konta',
                'recover_password' => 'Przypomnij hasło',
                'favourite' => 'Ulubione',
                'customer_login' => 'Logowanie',
                'orders_history' => 'Historia transakcji',
				'your_subscriptions' => 'Twoje abonamenty',
        ),

        'description' => array(
                'create_account' => 'Rejestracja',
                'customer_register_login' => 'Logowanie',
                'edit_account' => 'Edycja danych',
                'change_password' => 'Zmień hasło',
                'delete_password' => 'Usuwanie konta',
                'recover_password' => 'Przypomnij hasło',
                'favourite' => 'Ulubione',
                'customer_login' => 'Logowanie',
                'orders_history' => 'Historia transakcji',
				'your_subscriptions' => 'Twoje abonamenty',
        ),

        'keywords' => array(
                'create_account' => 'Rejestracja',
                'customer_register_login' => 'Logowanie',
                'edit_account' => 'Edycja danych',
                'change_password' => 'Zmień hasło',
                'delete_password' => 'Usuwanie konta',
                'recover_password' => 'Przypomnij hasło',
                'favourite' => 'Ulubione',
                'customer_login' => 'Logowanie',
                'orders_history' => 'Historia transakcji',
				'your_subscriptions' => 'Twoje abonamenty',
        ),



        'titles' => array(
                'customers_index' => 'Lista klientów - 4dminix CMS by Olicom',
                'edit_customer' => 'Edycja klienta - 4dminix CMS by Olicom',
        ),

        'logout' => 'Wyloguj',
        'delete' => 'Usuń',
        'selected' => 'Zaznaczone',
        'last_name' => 'Nazwisko',
        'first_name' => 'Imię',
        'email' => 'E-mail',
        'actions' => 'Opcje',
        'back' => 'Wróć',
        'save_changes' => 'ZAPISZ',
        'client_data' => 'Dane klienta',
        'registration' => 'Rejestracja',
        'register' => 'Neues Konto erstellen',
        'login' => 'Zaloguj >>',
        'login_title' => 'Logowanie',
        'password_recover_title' => 'Resetowanie hasła',
        'your_data' => 'Twoje dane',
        'orders_history' => 'Historia transakcji',
        'order_details' => 'Szczegóły zamówienia',
        'order_number' => 'Zamówienie nr - ',
		'your_subscriptions' => 'Twoje abonamenty',

        'gender' => 'Płeć',
        'male' => 'Mężczyzna',
        'female' => 'Kobieta',
        'company_name' => 'Nazwa firmy',
        'nip' => 'Numer NIP',
        'city' => 'Miejscowość',
		'adres' => 'Adres',
		'postcode' => 'Kod pocztowy',
        'zip' => 'Kod pocztowy',
		'adres_dost' => 'Adres dostawy',
		'adres_inny' => 'zaznacz jeżeli adres jest inny niż adres klienta',
        'address' => 'Adres',
        'state' => 'Województwo',
        'www' => 'Strona www',
		'phone' => 'Telefon',
        'phone_no' => 'Nr telefonu',
        'fax_no' => 'Nr faxu',
        'mobile_no' => 'Nr tel. komórkowego',
        'delivery_address' => 'Adres wysyłkowy',
        'invoice_address' => 'Adres do faktury',
        'country' => 'Kraj',
        'rebate' => 'Rabat',
        'change_password' => 'Zmień hasło',
		'reg_accept' => 'Akceptuje ',
		'regulamin' => 'regulamin',
		'and' => ' i ',
		'policy' => 'politykę prywatności',
		'reg_accept2' => 'Wyrażam zgodę na przetwarzanie moich danych osobowych zawartych w niniejszym formularzu zgodnie z ustawą z dnia 29.08.1997 r. o ochronie danych osobowych (Dz. U. z 2002r. Nr 101, poz. 926 ze zm.) w celu udostępniania konta w serwisie oraz w zakresie realizacji zamówienia dokonywanego w serwisie oraz w prawnie usprawiedliwionym celu Administratora. Przysługuje mi prawo do wglądu do swoich danych oraz ich poprawiania lub żądania ich usunięcia.',
		'accept3'=>'Wyrażam zgodę na otrzymywanie newslettera z informacjami handlowymi',
		'req_fields' =>'Pola wymagane',
		'reg_accept2_nologgin' => 'Wyrażam zgodę na przetwarzanie moich danych osobowych zawartych w niniejszym formularzu zgodnie z ustawą z dnia 29.08.1997 r. o ochronie danych osobowych (Dz. U. z 2002r. Nr 101, poz. 926 ze zm.) w zakresie realizacji zamówienia dokonywanego w serwisie oraz w prawnie usprawiedliwionym celu Administratora. Podanie danych jest dobrowolne. Przysługuje mi prawo do wglądu do swoich danych oraz ich poprawiania lub żądania ich usunięcia.',

        'account_title' => 'Twoje konto',

        'email_repeat' => 'Powtórz e-mail',
        'password' => 'Hasło',
        'password_repeat' => 'Powtórz hasło',
        'password_recover' => 'Dalej',

        'edit_customer' => 'Edytuj klienta',

        'no_customers' => 'Brak klientów',

        'change_customer_details' => 'Zmień swoje dane adresowe',
        'change_details' => 'Zmień dane',
        'watch' => 'Zobacz',
        'favourite' => 'Ulubione',
        'no_favs' => 'Brak zamówień.',
        'basket' => 'Koszyk',
        'delete_account' => 'Usuń konto',

        'delete_account_title' => 'Usuwanie konta',

        'account_delete_info' => 'Wpisz hasło w celu usunięcia konta. Usuwając konto usuniesz wszystkie dane powiązane z tym kontem z serwisu.',

        'forgot_password' => 'Nie pamiętasz hasła?',
        'please_register' => 'zarejestruj się',
        'login_info' => 'Jeśli jeszcze nie posiadasz konta, a chcesz mieć ułatwienia w wypełnianiu formularzy',

        'change_password_title' => 'Zmień hasło',
        'old_password' => 'Stare hasło',
        'new_password' => 'Nowe hasło',
        'new_password_repeat' => 'Powtórz nowe hasło',

        'delete_success' => 'Usunięto klienta.',
        'delete_error' => 'Wystąpił błąd podczas usuwania klienta.',
        'update_producer_success' => 'Uaktualniono dane klienta.',
        'update_producer_error' => 'Wystąpił błąd podczas usuwania klienta.',
        'insert_customer_success' => 'Rejestracja przebiegła pomyślnie. Na podany adres e-mail została wysłana wiadomość potwierdzająca rejestracje w naszym sklepie. W celu kontynowania zakupów proszę się zalogować.',
        'insert_customer_error' => 'Wystąpił błąd podczas rejestracji.',

        'client_delivery_data' => 'Dane do wysyłki',
        'client_invoice_data' => 'Dane do faktury',

        'validation' => array(
                'following_errors' => 'Wystąpiły następujące błędy',
                'error_customer_email_empty' => 'Pole <strong>E-mail</strong> nie może być puste.',
                'error_customer_email_repeat_empty' => 'Pole <strong>Powtórz e-mail</strong> nie może być puste.',
                'error_customer_password_empty' => 'Pole <strong>Hasło</strong> nie może być puste.',
                'error_customer_password_repeat_empty' => 'Pole <strong>Powtórz hasło</strong> nie może być puste.',
                'error_customer_password_too_short' => 'Hasło musi składać się minimum z 6 znaków.',
                'error_customer_password_repeat_too_short' => 'Powtórzone hasło musi składać się minimum z 6 znaków.',
                'error_customer_email_format' => 'Nieprawidłowy format adresu <strong>E-mail</strong>.',
                'error_customer_email_repeat_format' => 'Nieprawidłowy format adresu w polu <strong>Powtórz e-mail</strong>.',
                'error_wrong_customer_email_repeat' => 'Adresy e-mail muszą być jednakowe.',
                'error_wrong_customer_password_repeat' => 'Hasła muszą być jednakowe.',
                'customer_exists' => 'Klient o podanym e-mailu już istnieje.',
                'customer_not_exists' => 'Klient o podanym e-mailu nie istnieje.',
                'error_customer_exists' => 'Wystąpił błąd podczas sprawdzania czy klient już istnieje.',

                'wrong_email_or_password' => 'Nieprawidłowy adres e-mail lub hasło.',
                'success_login' => 'Zostałeś poprawnie zalogowany.',

                'error_logout' => 'Wystąpił błąd podczas wylogowywania.',
                'success_logout' => 'Zostałeś poprawnie wylogowany.',

                'customer_email_not_exist' => 'Podany adres email nie istnieje w bazie danych.',
                'success_recover_password' => 'Na podany adres e-mail zostało wysłane nowe hasło.',
                'error_recover_password' => 'Wystąpił błąd podczas generowania nowego hasła.',


                'error_old_password_empty' => 'Pole <strong>Stare hasło</strong> nie może być puste.',
                'error_new_password_empty' => 'Pole <strong>Nowe hasło</strong> nie może być puste.',
                'error_new_password_repeat_empty' => 'Pole <strong>powtórz nowe hasło</strong> nie może być puste.',
                'error_customer_old_password_too_short' => 'Stare hasło musi składać się minimum z 6 znaków.',
                'error_customer_new_password_too_short' => 'Nowe hasło musi składać się minimum z 6 znaków.',
                'error_customer_new_password_repeat_too_short' => 'Powtórzone hasło musi składać się minimum z 6 znaków.',
                'error_wrong_password' => 'Nieprawidłowe hasło.',
                'error_wrong_new_password_repeat' => 'Powtórzone hasło i nowe hasło muszą być jednakowe.',
                'error_reg_not_confirmed' => 'Musisz zaakceptować <strong>regulamin</strong>!',
				'error_reg_not_confirmed2' => 'Musisz zaakceptować <strong>zgodę na przetwarzanie danych osobowych</strong>!',

                'delete_from_fav_success' => 'Usunięto z ulubionych.',
                'delete_from_fav_error' => 'Wystąpił błąd podczas usuwania z ulubionych.',

                'delete_account_success' => 'Konto zostało usunięte.',
                'delete_account_error' => 'Wystąpił błąd podczas usuwania konta.',

                'please_login_to_add_to_fav' => 'Musisz się zalogować żeby dodać produkt do ulubionych.',

        ),
        'different_delivery_address' => 'Inny adres dostawy',
        'different_invoice_address' => 'Inne dane do faktury',
        'invoice' => 'Faktura VAT',
        'customer_email' => 'Email',
        'customer_city' => 'Miasto',
        'customer_zip' => 'Kod pocztowy',
        'customer_address' => 'Adres',
        'customer_state' => 'Województwo',
        'customer_phoneno' => 'Numer telefonu',
        'order_notes' => 'Uwagi do zamówienia',
        'delivery_first_name' => 'Imię',
        'delivery_last_name' => 'Nazwisko',
        'delivery_email' => 'Email',
        'delivery_company_name' => 'Nazwa firmy',
        'delivery_nip' => 'NIP',
        'delivery_city' => 'Miasto',
        'delivery_zip' => 'Kod pocztowy',
        'delivery_state' => 'Województwo',
        'delivery_country' => 'Państwo',
        'delivery_phoneno' => 'Numer telefonu',
        'delivery_faxno' => 'Numer faksu',
        'delivery_mobileno' => 'Numer telefonu komórkowego',
        'invoice_first_name' => 'Imię do faktury',
        'invoice_last_name' => 'Nazwisko do faktury',
        'invoice_email' => 'Email do faktury',
        'invoice_company_name' => 'Nazwa firmy do faktury',
        'invoice_nip' => 'NIP do faktury',
        'invoice_city' => 'Miasto do faktury',
        'invoice_zip' => 'Kod pocztowy do faktury',
        'invoice_state' => 'Województwo do faktury',
        'invoice_country' => 'Państwo do faktury',
        'invoice_phoneno' => 'Numer telefonu do faktury',
        'invoice_faxno' => 'Numer faksu',
        'invoice_mobileno' => 'Numer telefonu komórkowego',
        
        'field_required' => 'Pola wymagane',
    
        'password_recovery' => 'Jeśli nie pamiętasz hasła lub chcesz je zmienić wprowadz poniżej adres e-mail.',
    
        'user_registered' => array(
            'mail_title' => 'Serdecznie witamy w gronie naszych klientów.',
            'customer_details' => 'Podczas rejestracji podałeś następujące dane:',
            'login' => 'Login:',
            'password' => 'Hasło:',
            'safe_details' => 'Prosimy o zachowanie tych danych w bezpiecznym miejscu.',
            'confirm_click' => 'Aby potwierdzić rejestrację i tym samym aktywować konto należy kliknąć w link poniżej lub przekleić go do przeglądarki internetowej:',
            'update_details' => 'Celem usprawnienia korzystania z witryny w przyszłości, prosimy o uzupełnienie danych w panelu zarządzania kontem. Możesz tego dokonać po zalogowaniu się i wybraniu opcji edycji danych konta.',
        ),
        'account_confirmed' => 'Twoje konto zostało aktywowane.',
        'confirm_error' => 'Nieprawidłowy ciąg weryfikacyjny lub konto zostało już aktywowane.',
    
);